version: '3.7'
services: 
   
    eureka-server:
        image: eureka-server
        ports: 
            - "8761:8761"
        restart: always
       
        networks:
            - app-network
    
    account:
        image: account
        ports: 
            - "8080:8080"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
                
        depends_on:
            - eureka-server
        networks:
            - app-network
 
    loan:
        image: loan
        ports: 
            - "8081:8081"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
        depends_on:
            - eureka-server
        networks:
            - app-network

    zuul-gateway:
        image: zuul-gateway
        ports: 
            - "8083:8083"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
        depends_on:
            - eureka-server
        networks:
            - app-network
 
# Networks to be created to facilitate communication between containers
networks:
    app-network: